//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Macellum_Remake.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arter
    {
        public Arter()
        {
            this.Fisks = new HashSet<Fisk>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Fisk> Fisks { get; set; }
    }
}
