//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Macellum_Remake.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBConnectionContainer : DbContext
    {
        public DBConnectionContainer()
            : base("name=DBConnectionContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Trip> Trips { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<Password> Passwords { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<Fisk> Fisks { get; set; }
        public DbSet<Arter> Arters { get; set; }
        public DbSet<Havn> Havns { get; set; }
        public DbSet<FuleCost> FuleCosts { get; set; }
        public DbSet<ActiveSessionId> ActiveSessionIds { get; set; }
    }
}
